import './styles/reset.css'
import './styles/globals.css'
import clsx from 'clsx'
import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import Header from './components/Header/Header'
import styles from './layout.module.scss'

const notojp = Noto_Sans_JP({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className={clsx(notojp.className, styles.body)}>
        <Header />
        {children}
      </body>
    </html>
  )
}
